name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin' # Or 'zulu', 'adopt', etc.
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build # Runs all 'check' tasks, including lint and unit tests

    # If you want to run unit tests separately (and more explicitly):
    # - name: Run unit tests
    #   run: ./gradlew testDebugUnitTest

    # Optional: Upload build artifacts (e.g., an APK if you built one)
    # - name: Upload APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-debug.apk
    #     path: app/build/outputs/apk/debug/app-debug.apk