name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode google-services.json (Linux)
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          echo "Creating google-services.json for Linux runner"
          FILE_PATH="app/google-services.json"
          mkdir -p "$(dirname "$FILE_PATH")"
          echo "Writing google-services.json to $FILE_PATH"
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 --decode > $FILE_PATH
          echo "google-services.json created successfully."

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Combined build and test step for debug variant
      - name: Build and run unit tests for Debug
        #env:
        #  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8"
        run: ./gradlew :app:assembleDebug :app:testDebugUnitTest

    # Optional: Upload build artifacts (e.g., APK)
    # - name: Upload Debug APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-debug
    #     path: app/build/outputs/apk/debug/app-debug.apk # Adjust path as needed

    # Optional: Upload test reports
    # - name: Upload Debug Test Reports
    #   if: always() # Always run this step to upload reports even if tests fail
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: debug-unit-test-reports
    #     path: app/build/reports/tests/testDebugUnitTest/ # Adjust path as needed
